accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/", views.detail, name="detail"),
    path("signup/", views.signup, name="signup"),
    path("update/", views.update, name="update"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views

# from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),  # new
    path("", include("pages.urls")),
    path("articles/", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )
    # add additional fields in here

    def __str__(self):
        return self.email

    @property
    def full_name(self):
        return f"{self.last_name}{self.first_name}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import get_user_model
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.


def detail(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    context = {"user": user}
    return render(request, "accounts/detail.html", context)


@login_required
def follow(request, pk):
    # 프로필에 해당하는 유저를 로그인한 유저가!
    user = get_user_model().objects.get(pk=pk)
    if request.user == user:
        messages.warning(request, "스스로 팔로우 할 수 없습니다.")
        return redirect("accounts:detail", pk)
    if request.user in user.followers.all():
        # (이미) 팔로우 상태이면, '팔로우 취소'버튼을 누르면 삭제 (remove)
        user.followers.remove(request.user)
    else:
        # 팔로우 상태가 아니면, '팔로우'를 누르면 추가 (add)
        user.followers.add(request.user)
    return redirect("accounts:detail", pk)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  # ModelForm의 save 메서드의 리턴값은 해당 모델의 인스턴스다!
            auth_login(request, user, backend='django.contrib.auth.backends.ModelBackend')  # 로그인
            return redirect("articles:index")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        # AuthenticationForm은 ModelForm이 아님!
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 세션에 저장
            # login 함수는 request, user 객체를 인자로 받음
            # user 객체는 어디있어요? 바로 form에서 인증된 유저 정보를 받을 수 있음
            auth_login(request, form.get_user())
            # http://127.0.0.1:8000/accounts/login/?next=/articles/1/update/
            # request.GET.get('next') : /articles/1/update/
            return redirect(request.GET.get("next") or "articles:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    messages.warning(request, "로그아웃 하였습니다.")
    return redirect("articles:index")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)

accounts/templates/accounts/detail.html
{% load django_bootstrap5 %}
{% load static %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">

<body class="py-5 text-center parallax cover gradient-overlay" style="background-image: url(&quot;https://mir-s3-cdn-cf.behance.net/project_modules/1400/29e111149039507.62e042179696c.jpg&quot;); position: relative; background-position: 50% calc(50% + 50.6px); background-size: cover;">
<a href='/' style='font-weight:bold' type="button" class="btn btn-warning">🏠HOME</a>

    <div class="container d-flex flex-column" >
      <div class="row my-auto">
        <div class="row col-12 justify-content-center mt-3">
            <div class="card text-center" style="width: 25rem;">
                <div class="card-body">
                    <h2 class="card-title">{{ user.username }}'s Profile</h5>
                    <p class="card-text">{{ user.email }}</p>
                    {% if request.user != user %}
                    <a style="text-decoration:none; color:blue;" class="follow-implement" href="{% url 'accounts:follow' user.pk %}">
                        {% if request.user in user.followers.all %}
                        <i class="bi bi-backspace-fill"> Unfollow!</i>
                        {% else %}
                        <i class="bi bi-check-square-fill"> Follow!</i>
                        {% endif %}
                    </a>
                    {% endif %}
                </div>
                <div class='follow' style='float:left; margin-top:1rem;'>
                    <dl>
                        <dd>
                            <p style='font-weight:bolder'>following</p>
                            <span>{{ user.followings.count }}</span>
                        </dd>
                        <dd> 
                            <p style='font-weight:bolder'>follower</p>
                            <span>{{ user.followers.count }}</span>
                        </dd>
                    </dl>
                </div>
            </div>
         </div>
        </div>
      </div>
    </div>
    <div class="section-overlapping">
    <div class="container"></div>
    </div>
    <div>
    <div class="container">
        <div class="row"></div>
    </div>
    </div>
    </div>
    <div class="py-5">
    <div class="container">
      <div class="py-3">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-center"> <i class="d-block fa fa-stop-circle mb-3 text-muted fa-3x"></i>
              <p> <a href="https://goo.gl/maps/AUq7b9W7yYJ2" target="_blank"> Book Review Service <br>2022</a> </p>
              <p> <a href="tel:+246 - 542 550 5462">Multicampus</a> </p>
              <p class="mb-0"> <a href="mailto:info@pingendo.com">reading@kakao.com</a> </p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 d-flex align-items-center justify-content-center my-3"> <a href="#">
                <i class="d-block fa fa-facebook-official text-muted fa-lg mr-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-instagram text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-google-plus-official text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-pinterest-p text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-reddit text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-twitter text-muted fa-lg ml-2"></i>
              </a> </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-center" style="">
              <p class="mb-0">©22 차화영 &amp; 임수경</p>
            </div>
            </div>
            </div>
        </div>
        </div>
    </div>
</body>

accounts/templates/accounts/login.html
{% load django_bootstrap5 %}
{% load static %}
<!-- CSS only -->

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">


<body style="background-image: url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/06a77b144457079.628ce354af612.png')">

  <div class="row">
    <div class="p-5 col-md-7 d-flex flex-column justify-content-center">
        
    </div>
    <div class="p-5 col-md-5">
      <h3 class="mb-3" style="color:3C2317; font-weight:bolder">Log in!</h3>
      <form style="color: 3C2317; font-weight:bolder" action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="col-lg-10">
      
      {% bootstrap_button button_class="btn btn-outline-warning" style="font-weight:bold" button_type="reset" content="Cancel" %}
      {% bootstrap_button button_class="btn btn-warning" style="font-weight:bold" button_type="submit" content="Log in" %}
      </div>
    </div>
    </div>
  </div>

</body>

accounts/templates/accounts/signup.html
{% load django_bootstrap5 %}
{% load static %}
<!-- CSS only -->

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">


  <div style="background-image: url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/4b34c7151484215.630d0ab44b86d.jpg')">
      <div class="row">
        <div class="p-5 col-md-7 d-flex flex-column justify-content-center">
          <h4 style="color:FFE7CC; font-weight:bolder" class="display-4 mb-3">가면산장 살인사건 </h4>
          <p style="color:FFE7CC" class="mb-5 lead">"도모미 언니를 배신하지 말라고 그렇게 부탁했는데." 
          <br>다카유키는 바닥에서 일어나 "이제 막이 내렸잖아." 하고는 걸음을 내디뎠다.
          <br>별장을 나설 때 누군가가 보고 있는 것 같아 뒤돌아보았다.
          <br>그러나 아무도 없었다.
          <br>그리고 여기 왔을 때는 분명히 있었던 현관문 위의
          <br>가면도 이미 사라지고 없었다.</p>
        </div>
          <div class="p-5 col-md-5">
          <h3 class="mb-3" style="color:white; font-weight:bolder">Join Us!</h3>
          <form style="color: white;" action="" method="POST">
          
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="col-lg-10">
          {% bootstrap_button button_class="btn btn-outline-success" style="font-weight:bold" button_type="reset" content="Cancel" %}
          {% bootstrap_button button_class="btn btn-success" style="font-weight:bold" button_type="submit" content="Sign up" %}
          
          </div>
      </div>
    </div>
  </div>

  <div class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center"> <i class="d-block fa fa-stop-circle mb-3 text-muted fa-3x"></i>
          <p> <a href="https://goo.gl/maps/AUq7b9W7yYJ2" target="_blank"> Book Review Service 2022</a> </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center" style="">
          <p class="mb-0">©22 차화영 &amp; 임수경</p>
        </div>
      </div>
    </div>
  </div>