accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/", views.detail, name="detail"),
    path("signup/", views.signup, name="signup"),
    path("update/", views.update, name="update"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

articles/urls.py
# URL설정을 app 단위로!
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    # http://127.0.0.1:8000/articles/
    path("", views.index, name="index"),
    # http://127.0.0.1:8000/articles/new/
    # path('new/', views.new, name='new'),
    # http://127.0.0.1:8000/articles/create/
    path("create/", views.create, name="create"),
    # http://127.0.0.1:8000/articles/1/ : 1번글
    # http://127.0.0.1:8000/articles/3/ : 3번글
    path("<int:pk>/", views.detail, name="detail"),
    # http://127.0.0.1:8000/articles/1/update/ : 1번글 수정
    # http://127.0.0.1:8000/articles/3/update/ : 3번글 수정
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/like/", views.like, name="like"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views

# from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),  # new
    path("", include("pages.urls")),
    path("articles/", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from imagekit.processors import ResizeToFill
from imagekit.models import ProcessedImageField
from django.conf import settings


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "image"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]

articles/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Article
from .forms import ArticleForm
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST, require_safe

# Create your views here.
@require_safe
def index(request):
    articles = Article.objects.order_by("-pk")
    context = {"articles": articles}
    return render(request, "articles/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user
            article.save()
            messages.success(request, "글 작성이 완료되었습니다.")
            return redirect("articles:index")

    else:
        article_form = ArticleForm()
    context = {"article_form": article_form}
    return render(request, "articles/form.html", context=context)


@login_required
def detail(request, pk):
    # 특정 글을 가져온다.
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    # template에 객체 전달
    context = {
        "article": article,
        "comments": article.comment_set.all(),
        "comment_form": comment_form,
    }
    return render(request, "articles/detail.html", context)


@login_required
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.user:
        if request.method == "POST":
            # POST : input 값 가져와서, 검증하고, DB에 저장
            article_form = ArticleForm(request.POST, request.FILES, instance=article)
            if article_form.is_valid():
                # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
                article_form.save()
                messages.success(request, "글이 수정되었습니다.")
                return redirect("articles:detail", article.pk)
            # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 article_form을 랜더링
        else:
            # GET : Form을 제공
            article_form = ArticleForm(instance=article)
        context = {"article_form": article_form}
        return render(request, "articles/form.html", context)
    else:
        # 작성자가 아닐 때
        # (1) 403 에러메시지를 던져버린다.
        # from django.http import HttpResponseForbidden
        # return HttpResponseForbidden()
        # (2) flash message 활용!
        messages.warning(request, "작성자만 수정할 수 있습니다.")
        return redirect("articles:detail", article.pk)


@login_required
def comment_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
    return redirect("articles:detail", article.pk)


@login_required
def like(request, pk):
    article = get_object_or_404(Article, pk=pk)
    # 만약 로그인한 유저(request.user)가 이 글을 좋아요 눌렀다면,
    if request.user in article.like_users.all():
        # 좋아요 삭제하고
        article.like_users.remove(request.user)
        is_liked = False
    else:  # 좋아요 누르지 않은 상태라면 좋아요에 추가하고
        article.like_users.add(request.user)
        is_liked = True
        # 상세 페이지로 redirect
        context = {"isLiked": is_liked, "likeCount": article.like_users.count()}
    return redirect("articles:detail", article.pk)


def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        article.delete()
        return redirect("articles:index")
    context = {"article": article}
    return render(request, "articles/detail.html", context)

articles/templates/articles/detail.html
{% load django_bootstrap5 %}
{% load static %}

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>REVIEW</title>
  <meta name="author" content="Pingendo">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="wireframe.css" type="text/css">
</head>

<!-- nav -->
<nav class="navbar navbar-dark bg-primary">
  <div class="container d-flex justify-content-center"> <a class="navbar-brand" href="#">
      <i class="fa d-inline fa-lg fa-circle-o"></i>
      <b>Comfortable Books And Articles</b>
    </a> </div>
</nav>

<!-- 글 detail -->
<div class="container">
  <div class="m-2">
  {% block content %} 
  <h1 class="d-flex m-4 mb-0">{{ article.title }}</h1>
  {% if request.user == article.user %}
  <p>
    <button type="button" class="btn btn-warning">
      <a class="m-4 " style="color: #000;" href="{% url 'articles:update' article.pk %}">수정하기</a>
    </button>
  </p>
{% endif %}
  <hr>
  <p class="m-1">{{ article.pk }}번 게시글 | <a href="{% url 'accounts:detail' article.user.pk %}">{{ article.user.username }}</a></p>
  </div>
<div class="row m-1">
  <div class="row"><p>{{ article.created_at|date:"SHORT_DATETIME_FORMAT" }} | {{ article.updated_at|date:"y-m-d D" }}</p>
    <span>
      {% if request.user.is_authenticated %}
        <a class="like-heart" href="{% url 'articles:like' article.pk %}">
        {% if request.user in article.like_users.all %}
          <i class="bi bi-heart-fill"></i>
        {% else %}
          <i class="bi bi-heart"></i>
        {% endif %}</a>{{ article.like_users.count }}</span>
      {% endif %}

  </div>
</div>

<hr>
<div class="text-center">
  <p>{{ article.content }} </p>
{% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image }}" width="400" height="300">
{% endif %}
<hr>
<h4 class="my-3">댓글</h4>
{% if request.user.is_authenticated %}
<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form comment_form layout='inline'%}
  <br>
  {% bootstrap_button style='float:right' button_type="submit" content="OK" %}
</form>
{% endif %}
<hr>
</div>


{% for comment in comments %}
  <p> {{ comment.user.username }} | {{ comment.content }}</p>
  <hr>    
{% empty %}
  <p>댓글이 없어요😥</p>
{% endfor %}

<!-- <div class="">
  <footer>
    <img src="https://mir-s3-cdn-cf.behance.net/project_modules/1400/0a0133116900061.622c5ddbe76b7.png" alt="">
  </footer>
</div> -->


{% endblock %}


<div class="py-5">
  <div class="container">
    <div class="py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center"> <i class="d-block fa fa-stop-circle mb-3 text-muted fa-3x"></i>
            <p> <a href="https://goo.gl/maps/AUq7b9W7yYJ2" target="_blank"> Book Review Service <br>2022</a> </p>
            <p> <a href="tel:+246 - 542 550 5462">Multicampus</a> </p>
            <p class="mb-0"> <a href="mailto:info@pingendo.com">reading@kakao.com</a> </p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 d-flex align-items-center justify-content-center my-3"> <a href="#">
              <i class="d-block fa fa-facebook-official text-muted fa-lg mr-2"></i>
            </a> <a href="#">
              <i class="d-block fa fa-instagram text-muted fa-lg mx-2"></i>
            </a> <a href="#">
              <i class="d-block fa fa-google-plus-official text-muted fa-lg mx-2"></i>
            </a> <a href="#">
              <i class="d-block fa fa-pinterest-p text-muted fa-lg mx-2"></i>
            </a> <a href="#">
              <i class="d-block fa fa-reddit text-muted fa-lg mx-2"></i>
            </a> <a href="#">
              <i class="d-block fa fa-twitter text-muted fa-lg ml-2"></i>
            </a> </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center" style="">
            <p class="mb-0">©22 차화영 &amp; 임수경</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>

articles/templates/articles/form.html
{% load django_bootstrap5 %}
{% load static %}

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>REVIEW 작성</title>
  <meta name="author" content="Pingendo">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="wireframe.css" type="text/css">
</head>

{% comment %} nav bar {% endcomment %}
<nav class="navbar navbar-dark bg-primary">
  <div class="container d-flex justify-content-center">
    <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-circle-o"></i>
        <b>Comfortable Books And Articles</b>
    </a>
  </div>
</nav>  

<div class='container'>

  <div>
    {% block content %}
    {% if request.resolver_match.url_name == 'create' %}
    <h1 class='mt-3'> WRITE A REVIEW </h1>
    {% else %}
    <h1 class='mt-3'> EDIT </h1>
    {% endif %}
  </div>

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form article_form %}
    {% bootstrap_button style='float:right' button_type="submit" content="SAVE" %}
  </form>

  {% endblock %}
  <div class="py-5">
    <div class="container">
      <div class="py-3">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-center"> <i class="d-block fa fa-stop-circle mb-3 text-muted fa-3x"></i>
              <p> <a href="https://goo.gl/maps/AUq7b9W7yYJ2" target="_blank"> Book Review Service <br>2022</a> </p>
              <p> <a href="tel:+246 - 542 550 5462">Multicampus</a> </p>
              <p class="mb-0"> <a href="mailto:info@pingendo.com">reading@kakao.com</a> </p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 d-flex align-items-center justify-content-center my-3"> <a href="#">
                <i class="d-block fa fa-facebook-official text-muted fa-lg mr-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-instagram text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-google-plus-official text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-pinterest-p text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-reddit text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-twitter text-muted fa-lg ml-2"></i>
              </a> </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-center" style="">
              <p class="mb-0">©22 차화영 &amp; 임수경</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

articles/templates/articles/index.html
{% load static %}
{% load django_bootstrap5 %}

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="css/light-theme.css" id="theme-link" />

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>REVIEW</title>
  <meta name="author" content="Pingendo">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="wireframe.css" type="text/css">
</head>

<!-- <style>
  :root {
  color-scheme: light dark; /* both supported */
}
</style> -->

<script>
        // 링크 색 바꾸기
        function LinkSetColor(color){
            var alist = document.querySelectorAll('a');
            for(var i = 0; i < alist.length; i++)
                alist[i].style.color = color;
        }

        // 바디 글자색 바꾸기
        function BodySetColor(color){
            document.querySelector('body').style.color = color;
        }

        // 바디 배경색 바꾸기
        function BodySetBackgroundColor(color){
            document.querySelector('body').style.backgroundColor = color;
        }

        // 주간, 야간모드
        function day_night_handler(self) {
            var target = document.querySelector('body');
            if (self.value == 'day') {
                BodySetBackgroundColor('RGB(26,36,54)');
                BodySetColor('black');
                LinkSetColor('powderblue')
                self.value = 'night';
            }
            else {
                BodySetBackgroundColor('white');
                BodySetColor('black');
                LinkSetColor('blue')
                self.value = 'day';
            }
        }
</script>
<body>

  <nav class="navbar navbar-dark bg-primary">
    <div class="container d-flex justify-content-center"> <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-circle-o"></i>
        <b>Comfortable Books And Articles</b>
      </a> </div>
  </nav>
  
  
  <div class="py-4 text-center">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h1 class="display-3 text-capitalize">Reading Diary</h1>
          
          <p class="lead text-muted">What book did you read today?</p>
          <button class="btn" type="button">
            <a class=" btn btn-warning" href="{% url 'articles:create' %}" style="font-weight:bold">Writing</a></button>
            <br><input type="button" value="day" onclick="day_night_handler(this)">
            {% comment %} 기존에 bg-light라고 지정을 했기 때문에 dark모드를 해도 바뀌지 않았음 {% endcomment %}
        </div>
      </div>
    </div>
  </div>

<!-- 글작성하면 보이는 곳 -->
  <div class="py-4 ">
    <div class="container">
      <div class="row">
        {% for article in articles %}
        <div class="col-md-4 p-3">
          <div class="card box-shadow">
            {% if article.image %}
              <img class="card-img-top" src="{{ article.image.url }}">
            {% else %}
             <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="card-img-top">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{ article.title }}</h5>
              <p class="text-muted"><a href="{% url 'accounts:detail' article.user.pk %}">작성자 {{ article.user.username }}</a></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'articles:detail' article.pk %}" class="btn btn-outline-primary my-3">리뷰 보기</a>
                </div> <small class="text-muted">{{ article.updated_at|date:"y-m-d D" }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

  <div class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="pagination" style="">
            <li class="page-item"> <a class="page-link" href="#"> <span>«</span></a> </li>
            <li class="page-item active"> <a class="page-link" href="#">1</a> </li>
            <li class="page-item"> <a class="page-link" href="#">2</a> </li>
            <li class="page-item"> <a class="page-link" href="#">3</a> </li>
            <li class="page-item"> <a class="page-link" href="#">4</a> </li>
            <li class="page-item"> <a class="page-link" href="#"> <span>»</span></a> </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="carousel slide my-3" data-ride="carousel" id="carousel-1">
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active"> <img class="d-block img-fluid" src="https://mir-s3-cdn-cf.behance.net/project_modules/fs/76df0b152570167.63208befa0d05.png" data-holder-rendered="true">
                <div class="carousel-caption">
                  <h4>Travel</h4>
                  <p class="mb-0">Reading Tour Event&nbsp;</p>
                </div>
              </div>
              <div class="carousel-item"> <img class="d-block img-fluid" src="assets/styleguide/cover_3.jpg" data-holder-rendered="true">
                <div class="carousel-caption">
                  <h4>Caption #2</h4>
                  <p class="mb-0">Paragraph. Lorem ipsum dolor sit&nbsp;</p>
                </div>
              </div>
            </div> <a class="carousel-control-prev" role="#carousel-1" data-slide="prev" href="#carousel-1"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" role="button" data-slide="next" href="#carousel-1"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="carousel slide my-3" data-ride="carousel" id="carousel-2" data-interval="5000">
            <ol class="carousel-indicators">
              <li data-target="#carousel-2" data-slide-to="0" class="active">&nbsp;</li>
              <li data-target="#carousel-2" data-slide-to="1">&nbsp;</li>
              <li data-target="#carousel-2" data-slide-to="2">&nbsp;</li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active"> <img class="d-block img-fluid" src="https://mir-s3-cdn-cf.behance.net/project_modules/1400/4415e8152570167.63208bef9eff4.png" data-holder-rendered="true">
                <div class="carousel-caption">
                  <p class="lead">Take a break with reading</p>
                </div>
              </div>
              <div class="carousel-item"> <img class="d-block img-fluid" src="assets/styleguide/cover_4.jpg" data-holder-rendered="true">
                <div class="carousel-caption">
                  <p class="lead">Caption #2</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-4 p-3">
          <div class="card">
            <div class="card-body">
              <h5>A Card</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
          </div>
          <div class="card my-4">
            <div class="card-header bg-primary">
              <h5 class="mb-0 text-center">A Card Header</h5>
            </div>
            <div class="card-body">
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
            <div class="card-footer">A Card footer</div>
          </div>
        </div>
        <div class="col-md-4 p-3">
          <div class="bg-primary card"> <img class="img-fluid rounded-circle w-75 mx-auto mt-3" src="assets/styleguide/people_5.jpg" alt="Card image">
            <div class="card-body">
              <h4 class="card-title">Card</h4>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4 p-3">
          <div class="bg-primary card"> <img class="img-fluid rounded-circle w-75 mx-auto mt-3" src="assets/styleguide/people_5.jpg" alt="Card image">
            <div class="card-body">
              <h4 class="card-title">Card</h4>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="text-center mx-auto col-md-8"> <i class="fa d-block fa-bullseye fa-5x mb-4 text-info"></i>
          <p class="lead">Below is an example form built entirely with Bootstrap's form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5 bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="p-4 col-lg-12">
            <h4 class="mb-3 text-white">Heading 4</h4>
            <div class="blockquote text-muted">
              <p class="mb-0">Blockquoute -&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
              <div class="blockquote-footer">Someone famous in My memories</div>
            </div>
            <a class="btn btn-info" href="#">Button </a>
          </div>
        </div>
        <div class="col-md-6"><img class="img-fluid d-block" src="https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/55c24856026413.599d5aa8e02f3.jpg"></div>
      </div>
      <div class="row">
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="py-3">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-center"> <i class="d-block fa fa-stop-circle mb-3 text-muted fa-3x"></i>
              <p> <a href="https://goo.gl/maps/AUq7b9W7yYJ2" target="_blank"> Book Review Service <br>2022</a> </p>
              <p> <a href="tel:+246 - 542 550 5462">Multicampus</a> </p>
              <p class="mb-0"> <a href="mailto:info@pingendo.com">reading@kakao.com</a> </p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 d-flex align-items-center justify-content-center my-3"> <a href="#">
                <i class="d-block fa fa-facebook-official text-muted fa-lg mr-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-instagram text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-google-plus-official text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-pinterest-p text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-reddit text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-twitter text-muted fa-lg ml-2"></i>
              </a> </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-center" style="">
              <p class="mb-0">©22 차화영 &amp; 임수경</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  


  <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>

</html>